title: Raganova Cattery 
author: Mand Kittani
email: mandk@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Ragnova cattery we have the fulffiest kittens. 

# social links
twitter_username: mandzukic89 # DO NOT include the @ character, or else the build will fail!
github_username:  mandzukic89 # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
